"""Game configuration and constants."""

# Window settings
WINDOW_WIDTH = 1280
WINDOW_HEIGHT = 720
WINDOW_TITLE = "Doom Clone"
FPS_TARGET = 60

# OpenGL settings
OPENGL_MAJOR_VERSION = 3
OPENGL_MINOR_VERSION = 3

# Camera settings
FOV = 90.0
NEAR_PLANE = 0.1
FAR_PLANE = 1000.0
MOUSE_SENSITIVITY = 0.002
CAMERA_HEIGHT = 0.6  # Eye height in world units

# Player settings
PLAYER_SPEED = 5.0
PLAYER_SPRINT_MULTIPLIER = 1.5
PLAYER_RADIUS = 0.3
PLAYER_HEIGHT = 0.8
PLAYER_MAX_HEALTH = 100
PLAYER_MAX_ARMOR = 100

# Physics settings
GRAVITY = 20.0
JUMP_VELOCITY = 8.0

# Rendering settings
RENDER_DISTANCE = 100.0
TEXTURE_FILTERING = True

# Game settings
DEBUG_MODE = True
SHOW_FPS = True
